### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by MatthewAwesome** [GuoChen-WHU/react-native-pinch-zoom-view#2]
The documentation needs updating. The command to download/install from npm,

npm install react-native-pinch-zoom --save,  doesn't work. 

The following does: 
npm install react-native-pinch-zoom-view --save. 

Just a friendly heads up! Stay awesome!

**Comment by GuoChen-WHU** [comment]
My mistake_(:3J∠)_ , thanks~
