### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by aaleenmirza110** [GuoChen-WHU/react-native-pinch-zoom-view#3]
I am wrapping an image in pinch-zoom-view... Nothing is happening!

**Comment by GuoChen-WHU** [comment]
Please tell me which version of react native are you using? Can you show me the code?

**Comment by cbanning510** [comment]
Did not work for me on react-native 0.46.0

**Comment by GuoChen-WHU** [comment]
Well, I tried to update react-native to 0.46.0 in the example, it works fine. Have you tried the example?  Maybe you can try to run the example to see if it works.
