### ISSUE TITLE
Zoom doesn't work when inside a Modal

### ISSUE THREAD

**Issue by igorbrandao** [GuoChen-WHU/react-native-pinch-zoom-view#6]
First of all, thanks for this awesome lib! It was the first I found that truly uses only RN, and I searched a lot...

So now for the issue, I need zoom for an image inside a [Modal](https://facebook.github.io/react-native/docs/modal.html) and that doesnt seem to work. 😭

I have tested it outside and had no problems whatsoever, but `<PinchZoomView>` wont zoom if inside `<Modal>` tags.

**Comment by fritsvt** [comment]
Exactly the same issue here.
Aside from that this is an absolutely great package

**Comment by igorbrandao** [comment]
@fritsvt Since I had no replies, I went searching and found [this](https://github.com/ldn0x7dc/react-native-transformable-image) lib. For me it worked on `<Modal />` on both platforms (and using only pure RN as well, no yucky native configs).

Hope it helped you too.

**Comment by GuoChen-WHU** [comment]
Thank you for your response~. 

I think this is because Modal doesn't work with **panResponder** currently. facebook/react-native#14295. 

Try [this](https://github.com/magicismight/react-native-root-modal) lib instead of Modal, it should work.

**Comment by fritsvt** [comment]
@igorbrandao thanks, I solved it by putting it in a Modal from the react-navigation package ;)

**Comment by ghost** [comment]
Same issue
